### ISSUE TITLE
ModuleNotFoundError & ImportError

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#1]
I get this error when I run the code.

```
ModuleNotFoundError: No module named 'loss_functions'
from modules import GlobalAvgPool2d, ResidualBlock
ImportError: cannot import name 'GlobalAvgPool2d' from 'modules'
```

Why can't I find module loss_function.
Why can't I find GlobalAvgPool2d from the folder 'modules'.

Thank you

**Comment by DarioFontanel** [comment]
Hi, 
Thank you for pointing out these errors. I have removed the unused package _'loss_functions'_ and added the missing _'GlobalAvgPool2d'_ one. 
Please, let me know if you find any other import error.

Dario

**Comment by JackyLin7414** [comment]
HI,
I want to download 'resnet50_iabn_sync.pth.tar' from this [repo](https://github.com/mapillary/inplace_abn#training-on-imagenet-1k), but there only 'resnet50.pth.tar'.

Thank you
