### ISSUE TITLE
Pretrained model not found

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#2]
HI,
I want to download 'resnet50_iabn_sync.pth.tar' from this [repo](https://github.com/mapillary/inplace_abn#training-on-imagenet-1k), but there only 'resnet50.pth.tar'.

Thank you

_Originally posted by @JackyLin7414 in https://github.com/DarioFontanel/PAnS/issues/1#issuecomment-1037033984_

**Comment by JackyLin7414** [comment]
Hi,
I run the code before rename 'resnet50.pth.tar' to 'resnet50_iabn_sync.pth.tar'.
`python3 -m torch.distributed.launch --master_port 9999 --nproc_per_node=1 run.py --name test --default`

I am not sure if master_port is correct.

but, I get this error.

```
File "/home/PAnS/segmentation_module.py", line 30, in make_model 
del pre_dict['state_dict']['classifier.fc.weight']
KeyError: 'classifier.fc.weight'

```

Thank you

**Comment by DarioFontanel** [comment]
Hi,
I have uploaded the pretrained weights [here](https://drive.google.com/file/d/1w9ZkyHG7kByuN5Dr4S-qk88oEIFcX-A6/view?usp=sharing). Let me know if you find any kind of issue.

Dario

**Comment by JackyLin7414** [comment]
Hi,
I run the code below through the pretrained model
(resnet50_iabn_sync.pth.tar) .
python3 -m torch.distributed.launch --master_port 9999 --nproc_per_node=1
run.py  --default

when done the validation I get this error
Traceback (most recent call last):
File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in
_run_module_as_main return _run_code(code, main_globals, None,
File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in
_run_code exec(code, run_globals)
File
"/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py",
line 261, in <module> main()
File
"/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py",
line 256, in main raise
subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command
'['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py',
'--local_rank=0']' died with <Signals.SIGILL: 4>.

why it only runs validation no test
I run the code on single GPU.


Thank you

DarioFontanel ***@***.***> 於 2022年2月14日 週一 下午5:59寫道：

**Comment by JackyLin7414** [comment]
Hi,
I run the code below through the pretrained model (resnet50_iabn_sync.pth.tar) .
`python3 -m torch.distributed.launch --master_port 9999 --nproc_per_node=1 run.py  --default`

when done the validation I get this error
```
Traceback (most recent call last):
File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in
_run_module_as_main return _run_code(code, main_globals, None,
File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in
_run_code exec(code, run_globals)
File
"/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py",
line 261, in <module> main()
File
"/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py",
line 256, in main raise
subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command
'['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py',
'--local_rank=0']' died with <Signals.SIGILL: 4>.
```
Is the error due to DDP?

> Note that the pretrained weights are made on multiple-gpus with [DDP](https://pytorch.org/docs/stable/notes/ddp.html). In this repo DDP is used as well, but the model is firstly instantiated without DPP. So, please be sure to remove the DDP prefix module. contained in each key of weights dictionary before running the code. To accomplish this, simply rename each model key using key = key[7:].

why it only runs validation no test
I run the code on single GPU.
Does the code require tensorflow?

Thank you
