### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#3]
Hi,

My environment
- Ubuntu : 16.04
- GPU : GeForce GTX 1080 Ti (Single)
- ipykernel : 5.3.4
- ipython : 7.31.1
- Python : 3.8.5
- Pytorch : 1.6.0  py3.8_cuda10.2.89_cudnn7.6.5_0
- Torchvision : 0.7.0
- InPlaceAbn : 1.1.0
- Matplotlib :3.3.1
- Numpy : 1.19.1
- Tensorboard : 2.2.1
- tqdm : 4.50.2

I run by code below
`python3 -m torch.distributed.launch --master_port 9999 --nproc_per_node=1 run.py --name test --default`

When complete validation, get the error below
No run test
```

INFO:rank0: [!] Checkpoint saved.
INFO:rank0: [!] Best model Checkpoint saved.
INFO:rank0: *** Test the model on all seen classes...
INFO:rank0: *** Model restored from checkpoints/streethazards/Experiment.pth
  0%|                                                                                             | 0/1500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py', '--local_rank=0']' died with <Signals.SIGILL: 4>.

```

Data directory
 ```
~/PAnS/
    |----data/
       |----StreetHazards
             |----train/
                   |----annotations/
                          |----training
                                 |----t1-3
                    |----images
                          |----training
                                 |----t1-3
                    |----train.odgt
             |----validation/
                   |----annotations
                          |----validation
                                 |----t4
                    |----images
                          |----validation
                                 |----t4
                    |----validation.odgt
             |----test/
                    |----annotations
                          |----test
                                 |----t5
                                 |----t6
                    |----images
                          |----test
                                 |----t5
                                 |----t6
                    |----test.odgt

    |----pretrained/
            |----resnet50_iabn_sync.pth.tar
```

I can't run the code on the streethazards test dataset
How can I run this code on single GPU. 

Thank you

**Comment by JackyLin7414** [comment]
Hi,
Are the pretrained weights [here](https://drive.google.com/file/d/1w9ZkyHG7kByuN5Dr4S-qk88oEIFcX-A6/view?usp=sharing) trained on streethazards dataset?

Thank you

**Comment by DarioFontanel** [comment]
Hi, 
The command you used to run the code on a single GPU seems to be correct. Could you be a little bit more precise on the error? Which are the lines of the code that trigger the error?
 
Moreover, the pretrained weights refer only to the backbone which is pretrained on ImageNet.

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel
The error occurs at this line
https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/run.py#L302

The error message
```
INFO:rank0: [!] Checkpoint saved.
INFO:rank0: [!] Best model Checkpoint saved.
INFO:rank0: *** Test the model on all seen classes...
INFO:rank0: *** Model restored from checkpoints/streethazards/Experiment.pth
  0%|                                                                                             | 0/1500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py', '--local_rank=0']' died with <Signals.SIGILL: 4>.
```

I found the meaning of `died with <Signals.SIGILL: 4>` from [here](https://unix.stackexchange.com/questions/317492/list-of-kill-signals), maybe the code (trainer.py - def test) has illegal instructions?

Moreover, How can I run this code to reproduce your experiment on streethazards dataset.

Thank you

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel

> Hi, The command you used to run the code on a single GPU seems to be correct. Could you be a little bit more precise on the error? Which are the lines of the code that trigger the error?
> 
> Moreover, the pretrained weights refer only to the backbone which is pretrained on ImageNet.

Can I use  [pretrained weights ](https://drive.google.com/file/d/1w9ZkyHG7kByuN5Dr4S-qk88oEIFcX-A6/view?usp=sharing) on the streethazards dataset?

When I use the --no_pretrained command, the model is trained, validated and tested on the streethazards(train validation test) dataset.
Is this right?

Thank you

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel 

Note that the pretrained weights are made on multiple-gpus with [DDP](https://pytorch.org/docs/stable/notes/ddp.html). In this repo DDP is used as well, but the model is firstly instantiated without DPP. So, please be sure to remove the DDP prefix module. contained in each key of weights dictionary before running the code. To accomplish this, simply rename each model key using `key = key[7:]`

Sorry, I don't know what this means? Can you tell me?
Did the error occurs because of this?

Thank you
Jacky

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel 

I fixed the error by changing these two lines
https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/train.py#L204-L205

to 
 ```
prediction = torch.argmax(scores, dim=1) 
 anomaly_probabilities = torch.argmax(anomaly_scores, dim=1) 
```

but, I can't get the AUROC, AUPR, FPR95
![image](https://user-images.githubusercontent.com/99387573/157391102-7e1a0b12-7c49-4c25-9883-6adea6a8daf5.png)

I got AUROC(50), AUPR(1.200304), FPR95(100)
Are the codes has other errors?

Thank you 
Jacky

**Comment by DarioFontanel** [comment]
Hi, 

> Hi, @DarioFontanel The error occurs at this line
> 
> https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/run.py#L302
> 
> The error message
> 
> ```
> INFO:rank0: [!] Checkpoint saved.
> INFO:rank0: [!] Best model Checkpoint saved.
> INFO:rank0: *** Test the model on all seen classes...
> INFO:rank0: *** Model restored from checkpoints/streethazards/Experiment.pth
>   0%|                                                                                             | 0/1500 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
>     main()
>   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
>     raise subprocess.CalledProcessError(returncode=process.returncode,
> subprocess.CalledProcessError: Command '['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py', '--local_rank=0']' died with <Signals.SIGILL: 4>.
> ```
> 
> I found the meaning of `died with <Signals.SIGILL: 4>` from [here](https://unix.stackexchange.com/questions/317492/list-of-kill-signals), maybe the code (trainer.py - def test) has illegal instructions?
> 
> Moreover, How can I run this code to reproduce your experiment on streethazards dataset.
> 
> Thank you

Actually I think there is something wrong with you model, as I have just downloaded the entire repo from scratch and everything is working. 

> Hi, @DarioFontanel
> 
> Note that the pretrained weights are made on multiple-gpus with [DDP](https://pytorch.org/docs/stable/notes/ddp.html). In this repo DDP is used as well, but the model is firstly instantiated without DPP. So, please be sure to remove the DDP prefix module. contained in each key of weights dictionary before running the code. To accomplish this, simply rename each model key using `key = key[7:]`
> 
> Sorry, I don't know what this means? Can you tell me? Did the error occurs because of this?
> 
> Thank you Jacky

In these lines
https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/segmentation_module.py#L27-L34
we are loading the inplace-abn checkpoint without the DDP keys. Be sure to remove the DDP prefix 'module' if it is present in the dictionary you have downloaded.


> Hi, @DarioFontanel
> 
> > Hi, The command you used to run the code on a single GPU seems to be correct. Could you be a little bit more precise on the error? Which are the lines of the code that trigger the error?
> > Moreover, the pretrained weights refer only to the backbone which is pretrained on ImageNet.
> 
> Can I use [pretrained weights ](https://drive.google.com/file/d/1w9ZkyHG7kByuN5Dr4S-qk88oEIFcX-A6/view?usp=sharing) on the streethazards dataset?
> 
> When I use the --no_pretrained command, the model is trained, validated and tested on the streethazards(train validation test) dataset. Is this right?
> 
> Thank you

No, unfortunatelly it is not. Actually, the --no_pretrained commad is just used to select if you want you the backbone to be pretrained on Imagent or not. In the paper it is pretrained, so if you want to replicate the results you should not use the command. Moreover, please notice that the shared weights are related just to the pretraining phase of the backbone on ImageNet. You have to do your own training to get the trained model and reproduce the results.

> Hi, @DarioFontanel
> 
> I fixed the error by changing these two lines
> 
> https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/train.py#L204-L205
> 
> to
> 
> ```
> prediction = torch.argmax(scores, dim=1) 
> anomaly_probabilities = torch.argmax(anomaly_scores, dim=1) 
> ```
> 
> but, I can't get the AUROC, AUPR, FPR95 ![image](https://user-images.githubusercontent.com/99387573/157391102-7e1a0b12-7c49-4c25-9883-6adea6a8daf5.png)
> 
> I got AUROC(50), AUPR(1.200304), FPR95(100) Are the codes has other errors?
> 
> Thank you Jacky

If these changes are avoiding some errors I think that the real error is somewhere else, as those two lines are performing the same operations. The original version of the code is right so you should look somewhere else. Moreover, please refer to the above question in order to replicate the results. Please be sure to perform the training phase with the pretrained model on Imagent.

Dario

**Comment by JackyLin7414** [comment]
Thank you for the quick reply.

> Hi,
> 
> > Hi, @DarioFontanel The error occurs at this line
> > https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/run.py#L302
> > 
> > The error message
> > ```
> > INFO:rank0: [!] Checkpoint saved.
> > INFO:rank0: [!] Best model Checkpoint saved.
> > INFO:rank0: *** Test the model on all seen classes...
> > INFO:rank0: *** Model restored from checkpoints/streethazards/Experiment.pth
> >   0%|                                                                                             | 0/1500 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> >   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
> >     main()
> >   File "/home/anaconda3/envs/test_PAnS/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
> >     raise subprocess.CalledProcessError(returncode=process.returncode,
> > subprocess.CalledProcessError: Command '['/home/anaconda3/envs/test_PAnS/bin/python3', '-u', 'run.py', '--local_rank=0']' died with <Signals.SIGILL: 4>.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I found the meaning of `died with <Signals.SIGILL: 4>` from [here](https://unix.stackexchange.com/questions/317492/list-of-kill-signals), maybe the code (trainer.py - def test) has illegal instructions?
> > Moreover, How can I run this code to reproduce your experiment on streethazards dataset.
> > Thank you
> 
> Actually I think there is something wrong with you model, as I have just downloaded the entire repo from scratch and everything is working.
> 
> > Hi, @DarioFontanel
> > Note that the pretrained weights are made on multiple-gpus with [DDP](https://pytorch.org/docs/stable/notes/ddp.html). In this repo DDP is used as well, but the model is firstly instantiated without DPP. So, please be sure to remove the DDP prefix module. contained in each key of weights dictionary before running the code. To accomplish this, simply rename each model key using `key = key[7:]`
> > Sorry, I don't know what this means? Can you tell me? Did the error occurs because of this?
> > Thank you Jacky
> 
> In these lines
> 
> https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/segmentation_module.py#L27-L34
> 
> 
> we are loading the inplace-abn checkpoint without the DDP keys. Be sure to remove the DDP prefix 'module' if it is present in the dictionary you have downloaded.
> > Hi, @DarioFontanel
> > > Hi, The command you used to run the code on a single GPU seems to be correct. Could you be a little bit more precise on the error? Which are the lines of the code that trigger the error?
> > > Moreover, the pretrained weights refer only to the backbone which is pretrained on ImageNet.
> > 
> > 
> > Can I use [pretrained weights ](https://drive.google.com/file/d/1w9ZkyHG7kByuN5Dr4S-qk88oEIFcX-A6/view?usp=sharing) on the streethazards dataset?
> > When I use the --no_pretrained command, the model is trained, validated and tested on the streethazards(train validation test) dataset. Is this right?
> > Thank you
> 
> No, unfortunatelly it is not. Actually, the --no_pretrained commad is just used to select if you want you the backbone to be pretrained on Imagent or not. In the paper it is pretrained, so if you want to replicate the results you should not use the command. Moreover, please notice that the shared weights are related just to the pretraining phase of the backbone on ImageNet. You have to do your own training to get the trained model and reproduce the results.
> 
> > Hi, @DarioFontanel
> > I fixed the error by changing these two lines
> > https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/train.py#L204-L205
> > 
> > to
> > ```
> > prediction = torch.argmax(scores, dim=1) 
> > anomaly_probabilities = torch.argmax(anomaly_scores, dim=1) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but, I can't get the AUROC, AUPR, FPR95 ![image](https://user-images.githubusercontent.com/99387573/157391102-7e1a0b12-7c49-4c25-9883-6adea6a8daf5.png)
> > I got AUROC(50), AUPR(1.200304), FPR95(100) Are the codes has other errors?
> > Thank you Jacky
> 
> If these changes are avoiding some errors I think that the real error is somewhere else, as those two lines are performing the same operations. The original version of the code is right so you should look somewhere else. Moreover, please refer to the above question in order to replicate the results. Please be sure to perform the training phase with the pretrained model on Imagent.
> 
> Dario



Thank you for the quick reply.
I run this code on another environment (python=3.8.10 torch=1.6+cu101) and everything working.
My environment is same python and torch version, but the command `torch.max(dim=1)` will get illegal instruction.
I am confused why this error occurs.

Thank you so much
Jacky
