### ISSUE TITLE
Reproducibility of results

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#4]
Hi, @DarioFontanel 

I have run the code you provided for Anomaly Segmentation with the default parameters, following the instructions specified in the readme. I obtained the following results:
AUROC : 50
AUPR : 1.200304
FPR95 : 100

Can you help me understand what's going on here?

Thank you
Jacky

**Comment by DarioFontanel** [comment]
Hi,
Please refer to this comment: https://github.com/DarioFontanel/PAnS/issues/3#issuecomment-1066670800 .

Dario
