### ISSUE TITLE
How to get Anomaly Segmentation pictures

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#5]
Hi, @DarioFontanel 
When I rebuild the conda environment with python=3.7.0 pytorch=1.4.0 the code works like a charm.
Thank you. I appreciate it.

But, when I run the code below
`tensorboard --logdir logs/ --bind_all`

I can't find this results
![159136407-9e781d23-ea83-4938-9c5d-37b01ca75ad0](https://user-images.githubusercontent.com/99387573/159328674-a9f301a7-5314-4651-803d-9c587f883215.png)

How can I get it?

By the way, the directory `/logs/results` is empty.Is it right?

Thank you
Jacky

**Comment by DarioFontanel** [comment]
Hi Jacky,
Qualitative results are not implemented in this code base. We created them offline, by loading the trained weights of the model and visualizing the confidence. We used [imshow](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.imshow.html) as follows:

`imshow(confidence, interpolation='bilinear', cmap=matplotlib.cm.Blues, vmin=-1, vmax=1)
`

Dario

**Comment by JackyLin7414** [comment]
> Hi Jacky, Qualitative results are not implemented in this code base. We created them offline, by loading the trained weights of the model and visualizing the confidence. We used [imshow](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.imshow.html) as follows:
> 
> `imshow(confidence, interpolation='bilinear', cmap=matplotlib.cm.Blues, vmin=-1, vmax=1) `
> 
> Dario

Hi, @DarioFontanel 

Thank you for the quick reply.

Could you tell me where to put this line?
I can't find the confidence from this code. Where can I find it?

Is the `confidence `from this line array-like or PIL image?
`imshow(confidence, interpolation='bilinear', cmap=matplotlib.cm.Blues, vmin=-1, vmax=1)`

Thank you
Jacky
