### ISSUE TITLE
The color of the Anomaly Segmentation pictures

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#7]
Hi @DarioFontanel ,
I added this line like you said in https://github.com/DarioFontanel/PAnS/issues/5#issuecomment-1079902994
`plt.imshow(anomaly_probabilities.squeeze(0).cpu().numpy(), interpolation='bilinear', cmap=matplotlib.cm.Blues, vmin=-1, vmax=1)`

to here
https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/train.py#L206

But I get an image like this
![as](https://user-images.githubusercontent.com/99387573/168423347-3fc9c846-aae6-4510-8b86-5f5dd6c24e7d.png)

Color is not the same
![image](https://user-images.githubusercontent.com/99387573/168423624-48917fdb-bb6c-437e-9983-db347d16875c.png)

Can you tell me why?

Thank you. I appreciate it.

**Comment by DarioFontanel** [comment]
Hi, 
It might simply be due to scale factor multiplication. Let's try different options of vmin and vmax factors to increase/decrease the normalization (I would advise starting with 0.5) and see if this is the cause.

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel 
Can you tell me which image number you chose?

Thank you. I appreciate it.

Jacky

**Comment by DarioFontanel** [comment]
Hi, 
This list might contain some of the images reported in the final version of the paper, but I am not 100% sure because unfortunately I can't access the notebook updated version anymore. 
`list_idx = [475, 798, 998, 1024]`.

Let me know if that works.

Dario

**Comment by JackyLin7414** [comment]
Hi @DarioFontanel ,

The number of Anomaly Segmentation pictures is five instead of four.
I tried the list you provided. But all the images I get are different from yours.

Thank you. I appreciate it.

Jacky
