### ISSUE TITLE
About ground truth Semantic Segmentation images

### ISSUE THREAD

**Issue by JackyLin7414** [DarioFontanel/PAnS#8]
Hi, @DarioFontanel 
I have no idea how to get the ground truth Semantic Segmentation images.
Can you tell me. Thank you.
![image](https://user-images.githubusercontent.com/99387573/173288485-060baf99-6604-40ca-98b3-d6f6dabe2177.png)

I'm very grateful for your continuous help.
Jacky

**Comment by DarioFontanel** [comment]
Hi Jacky,
The following line shows how you can create and add them to the logger. The pipeline is the same for both GT and predicted masks. https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/run.py#L255

Dario

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel 
Thank you for the quick response.
https://github.com/DarioFontanel/PAnS/blob/fb604d01f9de57e83b2adfddf60e7a9fa6615bc6/run.py#L255

This line is for validation. 
Can you tell me how to use it for testing?

Thank you. I appreciate it.
Jacky

**Comment by DarioFontanel** [comment]
Hi,
It's exactly the same pipeline, you just only have to put test GTs in `target`.

Dario

**Comment by JackyLin7414** [comment]
Hi, @DarioFontanel 
Thank you for the quick response. Your answer is exactly what i want.
I appreciate it.

Jacky
